namespace: products-crud-api
products-crud-api:
  defines: runnable
  metadata:
    name: products-crud-api
    description: >-
      A product management API made with Nest.js that supports CRUD (Create,
      Read, Update, Delete) operations.
    icon: https://emojiapi.dev/api/v1/rocket.svg
  containers:
    products-crud-api:
      build: .
  services:
    app:
      container: products-crud-api
      port: <- $port
      host-port: <- $port
      publish: false
      protocol: TCP
      description: The port where the application runs
  connections:
    mongodb:
      target: aerospike/aerospike
      service: base-svc
  variables:
    port:
      env: PORT
      type: int
      description: Port where the app runs
      value: '3003'
    db-url:
      env: DB_URL
      type: string
      description: URL of the MongoDB database
      value: '!!!SETME!!!'
    db-host:
      env: DB_HOST
      type: string
      description: Host of the MongoDB database
      value: <- connection-hostname("mongodb")
    db-username:
      env: DB_USERNAME
      type: string
      description: Username for the MongoDB database
      value: '!!!SETME!!!'
    db-password:
      env: DB_PASSWORD
      type: string
      description: Password for the MongoDB database
      value: '!!!SETME!!!'
    db-port:
      env: DB_PORT
      type: int
      description: Port for MongoDB database
      value: <- connection-port("mongodb")
    db-name:
      env: DB_NAME
      type: string
      description: Name of the MongoDB database
      value: '!!!SETME!!!'
